#!/bin/bash

# CI Environment Setup Script for Intellicenter
# This script sets up the complete CI environment for testing and validation

set -e  # Exit on any error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
PYTHON_VERSION="3.13"
NODE_VERSION="20.x"
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
FRONTEND_DIR="$PROJECT_ROOT/frontend"
SCRIPTS_DIR="$PROJECT_ROOT/scripts"

# Logging function
log() {
    echo -e "${BLUE}[$(date '+%Y-%m-%d %H:%M:%S')]${NC} $1"
}

log_success() {
    echo -e "${GREEN}✓${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}⚠${NC} $1"
}

log_error() {
    echo -e "${RED}✗${NC} $1"
}

# Check if running in CI environment
is_ci() {
    [[ -n "$CI" || -n "$GITHUB_ACTIONS" || -n "$JENKINS_URL" ]]
}

# Check required commands
check_requirements() {
    log "Checking requirements..."
    
    local missing_commands=()
    
    # Check basic commands
    for cmd in python3 npm poetry git curl; do
        if ! command -v "$cmd" &> /dev/null; then
            missing_commands+=("$cmd")
        fi
    done
    
    if [ ${#missing_commands[@]} -ne 0 ]; then
        log_error "Missing required commands: ${missing_commands[*]}"
        exit 1
    fi
    
    log_success "All requirements satisfied"
}

# Set up Python environment
setup_python() {
    log "Setting up Python environment..."
    
    # Check Python version
    if ! python3 --version | grep -q "$PYTHON_VERSION"; then
        log_warning "Python $PYTHON_VERSION not found, installing..."
        # This would typically be handled by the CI environment
        # For local setup, you might want to use pyenv or similar
    fi
    
    # Install Poetry if not present
    if ! command -v poetry &> /dev/null; then
        log "Installing Poetry..."
        curl -sSL https://install.python-poetry.org | python3 -
        export PATH="$HOME/.local/bin:$PATH"
    fi
    
    # Navigate to project root
    cd "$PROJECT_ROOT"
    
    # Install dependencies
    log "Installing Python dependencies..."
    poetry install --no-interaction --no-ansi
    
    log_success "Python environment setup complete"
}

# Set up Node.js environment
setup_node() {
    log "Setting up Node.js environment..."
    
    # Navigate to frontend directory
    cd "$FRONTEND_DIR"
    
    # Install Node.js version if needed (handled by CI environment)
    log "Installing Node.js dependencies..."
    npm ci --prefer-offline --no-audit
    
    log_success "Node.js environment setup complete"
}

# Set up environment variables
setup_environment() {
    log "Setting up environment variables..."
    
    # Create .env file if it doesn't exist
    if [ ! -f "$PROJECT_ROOT/.env" ]; then
        log "Creating .env file..."
        cat > "$PROJECT_ROOT/.env" << EOF
# Intellicenter Environment Configuration
# This file is automatically generated by CI setup

# Python environment
PYTHONPATH="$PROJECT_ROOT:$PROJECT_ROOT/intellicenter"

# Logging
LOG_LEVEL=INFO
LOG_FORMAT=json

# Memory management
MEMORY_THRESHOLD_MB=7168
MAX_CONCURRENT_MODELS=2

# Testing
TEST_TIMEOUT=30
RETRY_COUNT=3

# Frontend
VITE_API_URL=http://localhost:8000
VITE_WS_URL=ws://localhost:8000/ws

# Demo configuration
DEMO_MODE=true
SCENARIO_TIMEOUT=180
EOF
    fi
    
    # Set CI-specific environment variables
    if is_ci; then
        export CI=true
        export PYTHONPATH="$PROJECT_ROOT:$PROJECT_ROOT/intellicenter"
        export LOG_LEVEL="INFO"
        export MEMORY_THRESHOLD_MB="7168"
        export MAX_CONCURRENT_MODELS="2"
        export TEST_TIMEOUT="30"
        export RETRY_COUNT="3"
        export DEMO_MODE="true"
        export SCENARIO_TIMEOUT="180"
        
        log_success "CI environment variables configured"
    else
        log_success "Local environment variables configured"
    fi
}

# Set up testing tools
setup_testing_tools() {
    log "Setting up testing tools..."
    
    cd "$PROJECT_ROOT"
    
    # Install Python testing tools
    log "Installing Python testing tools..."
    poetry run pip install pytest-cov pytest-xdist pytest-mock pytest-benchmark
    
    # Install frontend testing tools
    cd "$FRONTEND_DIR"
    log "Installing frontend testing tools..."
    npm install --save-dev @testing-library/react @testing-library/jest-dom @testing-library/user-event
    
    log_success "Testing tools setup complete"
}

# Set up validation tools
setup_validation_tools() {
    log "Setting up validation tools..."
    
    cd "$PROJECT_ROOT"
    
    # Install Python validation tools
    log "Installing Python validation tools..."
    poetry run pip install flake8 black mypy bandit safety
    
    # Install frontend validation tools
    cd "$FRONTEND_DIR"
    log "Installing frontend validation tools..."
    npm install --save-dev eslint-plugin-promise eslint-plugin-import
    
    log_success "Validation tools setup complete"
}

# Set up monitoring and profiling tools
setup_monitoring_tools() {
    log "Setting up monitoring and profiling tools..."
    
    cd "$PROJECT_ROOT"
    
    # Install Python monitoring tools
    log "Installing Python monitoring tools..."
    poetry run pip install psutil memory-profiler line-profiler
    
    # Create monitoring scripts
    mkdir -p "$SCRIPTS_DIR/monitoring"
    
    cat > "$SCRIPTS_DIR/monitoring/memory_monitor.py" << 'EOF'
#!/usr/bin/env python3
import psutil
import time
import json
from datetime import datetime

def monitor_memory(interval=5, duration=60):
    """Monitor memory usage over time"""
    results = []
    start_time = time.time()
    
    while time.time() - start_time < duration:
        memory_info = psutil.virtual_memory()
        process_info = psutil.Process().memory_info()
        
        result = {
            'timestamp': datetime.now().isoformat(),
            'memory_percent': memory_info.percent,
            'memory_used_mb': memory_info.used / 1024 / 1024,
            'memory_available_mb': memory_info.available / 1024 / 1024,
            'process_memory_mb': process_info.rss / 1024 / 1024
        }
        
        results.append(result)
        time.sleep(interval)
    
    return results

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description='Monitor memory usage')
    parser.add_argument('--interval', type=int, default=5, help='Monitoring interval in seconds')
    parser.add_argument('--duration', type=int, default=60, help='Monitoring duration in seconds')
    args = parser.parse_args()
    
    results = monitor_memory(args.interval, args.duration)
    
    with open('memory_monitoring_results.json', 'w') as f:
        json.dump(results, f, indent=2)
    
    print(f"Memory monitoring complete. Results saved to memory_monitoring_results.json")
EOF

    chmod +x "$SCRIPTS_DIR/monitoring/memory_monitor.py"
    
    log_success "Monitoring tools setup complete"
}

# Validate setup
validate_setup() {
    log "Validating CI setup..."
    
    cd "$PROJECT_ROOT"
    
    # Check Python environment
    log "Validating Python environment..."
    if ! poetry run python -c "import sys; print(f'Python version: {sys.version}')" > /dev/null 2>&1; then
        log_error "Python environment validation failed"
        exit 1
    fi
    
    # Check Node.js environment
    cd "$FRONTEND_DIR"
    log "Validating Node.js environment..."
    if ! npm run --silent lint > /dev/null 2>&1; then
        log_warning "Frontend linting validation failed, but continuing..."
    fi
    
    # Check essential imports
    cd "$PROJECT_ROOT"
    log "Validating essential imports..."
    poetry run python -c "
try:
    from intellicenter.core.memory_manager import MemoryOptimizer
    from intellicenter.core.event_bus import EventBus
    from intellicenter.agents.coordinator_agent import CoordinatorAgent
    print('✓ Core imports successful')
except ImportError as e:
    print(f'✗ Import error: {e}')
    exit(1)
"
    
    log_success "CI setup validation complete"
}

# Generate setup report
generate_report() {
    log "Generating setup report..."
    
    local report_file="$PROJECT_ROOT/ci-setup-report.txt"
    
    {
        echo "Intellicenter CI Setup Report"
        echo "=============================="
        echo "Generated: $(date)"
        echo ""
        echo "Environment Information:"
        echo "  Python Version: $(python3 --version)"
        echo "  Node.js Version: $(node --version)"
        echo "  Poetry Version: $(poetry --version)"
        echo "  NPM Version: $(npm --version)"
        echo ""
        echo "Project Structure:"
        echo "  Project Root: $PROJECT_ROOT"
        echo "  Frontend Directory: $FRONTEND_DIR"
        echo "  Scripts Directory: $SCRIPTS_DIR"
        echo ""
        echo "Dependencies:"
        echo "  Python Packages: $(poetry show --no-dev | wc -l) installed"
        echo "  Node.js Packages: $(cd "$FRONTEND_DIR" && npm list --depth=0 --prod | wc -l) installed"
        echo ""
        echo "Environment Variables:"
        echo "  CI: $CI"
        echo "  PYTHONPATH: $PYTHONPATH"
        echo "  LOG_LEVEL: $LOG_LEVEL"
        echo "  MEMORY_THRESHOLD_MB: $MEMORY_THRESHOLD_MB"
        echo "  MAX_CONCURRENT_MODELS: $MAX_CONCURRENT_MODELS"
        echo ""
        echo "Tools Available:"
        echo "  Python: pytest, flake8, black, mypy, bandit, safety"
        echo "  Node.js: eslint, vitest, @testing-library/*"
        echo "  Monitoring: memory-profiler, psutil"
        echo ""
        echo "Setup Status: COMPLETE"
    } > "$report_file"
    
    log_success "Setup report generated: $report_file"
}

# Main setup function
main() {
    log "Starting Intellicenter CI Environment Setup..."
    log "Project Root: $PROJECT_ROOT"
    
    # Check if we're in the right directory
    if [ ! -f "$PROJECT_ROOT/pyproject.toml" ] || [ ! -d "$PROJECT_ROOT/intellicenter" ]; then
        log_error "Project root not found. Please run this script from the project root directory."
        exit 1
    fi
    
    # Execute setup steps
    check_requirements
    setup_python
    setup_node
    setup_environment
    setup_testing_tools
    setup_validation_tools
    setup_monitoring_tools
    validate_setup
    generate_report
    
    log_success "CI Environment Setup Complete!"
    log_success "You can now run the demo tests with: ./scripts/run-demo-tests.sh"
}

# Handle script arguments
case "${1:-}" in
    "python")
        setup_python
        ;;
    "node")
        setup_node
        ;;
    "env")
        setup_environment
        ;;
    "test")
        setup_testing_tools
        ;;
    "validate")
        validate_setup
        ;;
    "report")
        generate_report
        ;;
    *)
        main
        ;;
esac